# Generated by Django 4.0.4 on 2022-04-21 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auther', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='library/static/uploads')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('appropriate', models.CharField(choices=[('under8', 'Under 8'), ('8-15', '8-15'), ('adults', 'Adults')], default='under8', max_length=50)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='auther.auther')),
            ],
        ),
    ]
